export enum ErrorCodes {
  GAME_NOT_FOUND = "GAME_NOT_FOUND",
  LANGUAGE_NOT_FOUND = "LANGUAGE_NOT_FOUND",
  SPY_MASTER_ALREADY_SET = "SPY_MASTER_ALREADY_SET",
  GAME_IS_NOT_RUNNING = "GAME_IS_NOT_RUNNING",
  NOT_PLAYERS_TURN = "NOT_PLAYERS_TURN",
}
